### ISSUE TITLE
检查更新无反应

### ISSUE THREAD

**Issue by Xiao-yux** [xi-yue-233/nonebot-plugin-pluginupdatecheck#3]
![image](https://github.com/xi-yue-233/nonebot-plugin-pluginupdatecheck/assets/79674967/130c8c3a-400c-4eaf-9ebb-e89154527041)

**Comment by Xiao-yux** [comment]
![image](https://github.com/xi-yue-233/nonebot-plugin-pluginupdatecheck/assets/79674967/233a105f-b17e-41a0-ba03-efd0f6fae5f3)

**Comment by xi-yue-233** [comment]
使用的是pip命令，如果你是虚拟环境的话可能用不了

**Comment by Xiao-yux** [comment]
用的nb自动创建的虚拟环境

**Comment by Xiao-yux** [comment]
难道全是最新版，所以没信息吗？

**Comment by xi-yue-233** [comment]
虚拟环境用不了，用的系统命令pip show来完成的

**Comment by Xiao-yux** [comment]
更新一下呗，用系统命令加入虚拟环境，然后在执行更新

**Comment by xi-yue-233** [comment]
我现在就是不知道怎么pip show进入虚拟环境，如果有方法的话请pr一下
